---
title: "STAT429_HW2"
author: "Michael Wieck-Sosa"
date: "9/27/2020"
output: html_document
---


```{r}

library(car)
library(lmtest)
library(stats)
library(dynlm)
library(forecast)
library(pautocorr)
library(tseries)
library(FinTS)
library(fGarch)
library(rugarch)

```


```{r}

#3 
path <- "C:/Users/mykul/Downloads/"
file <- paste(path,"m-mrk4608.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)#, fileEncoding = "UTF-16LE")
df <- data
df["date"] <- as.Date(as.character(data[["date"]]) , format = "%Y%m%d")
logReturns <- log(data["mrk"]+1) 


```


```{r}
#3 (i) 
acf(logReturns)
pacf(logReturns)
pautocorr.test(logReturns,lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)
```


```{r}
#3 (i) 
mrkFirstDiff <- diff(as.matrix(logReturns),differences = 1)
acf(mrkFirstDiff)
pacf(mrkFirstDiff)
pautocorr.test(mrkFirstDiff,lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)
```




```{r}
#3 (i) 
armaLogReturns <- arma(logReturns, order = c(8, 0))
summary(armaLogReturns)
plot(armaLogReturns)
acf(residuals(armaLogReturns), na.action=na.remove, lag.max = 10)
pacf(residuals(armaLogReturns), na.action=na.remove, lag.max = 10)

pautocorr.test(residuals(armaLogReturns),lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)

residArmaLogReturns <- residuals(armaLogReturns)
residArmaLogReturns <- residArmaLogReturns[!is.na(residArmaLogReturns)]
durbinWatsonTest(residArmaLogReturns)
Box.test(residuals(armaLogReturns), lag = 10, type = c("Ljung-Box"), fitdf = 0)




```

```{r}
# 3 (ii)
armaLogReturns <- arma(logReturns, order = c(8, 0))

ArchTest(residuals(armaLogReturns)^2, lags = 10, demean = TRUE) 

Box.test(residuals(armaLogReturns)^2, lag = 10, type = c("Ljung-Box"), fitdf = 0) 

# all p-values below 0.05
# ==> evidence of ARCH effects

```


```{r}
# 3 (iii)
# ARCH(1) = GARCH(1,0) has the lowest BIC score
# Information Criterion Statistics:
#     AIC       BIC       SIC      HQIC 
#-2.458707 -2.440246 -2.458739 -2.451594 
# also, ARCH 1-4 have the same lags: lag1, lag4, and lag8 that are significant at the 0.05 significance level for the PACF test

arch1LogReturns <- garchFit(formula = ~garch(1,0), data = logReturns, trace = F)
summary(arch1LogReturns)
acf(residuals(arch1LogReturns), na.action=na.remove)
pacf(residuals(arch1LogReturns), na.action=na.remove)
plot(residuals(arch1LogReturns))
pautocorr.test(residuals(arch1LogReturns),lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)

model = ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1, 0),
  submodel = NULL, external.regressors = NULL, variance.targeting = FALSE),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE, archm = FALSE,
  archpow = 1, arfima = FALSE, external.regressors = NULL, archex = FALSE),
  distribution.model = "norm", start.pars = list(), fixed.pars = list())

fit = ugarchfit(model, logReturns)
fit
acf(residuals(fit), na.action=na.remove)
pacf(residuals(fit), na.action=na.remove)
plot(residuals(fit))
pautocorr.test(residuals(fit),lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)
```
```{r}
# 3 (iv)
arch1LogReturns <- garchFit(formula = ~garch(1,0), data = logReturns, trace = F)
summary(arch1LogReturns)
predict(arch1LogReturns, n.ahead = 2)
```


```{r}
# 3 (v)
# t distributions for epsilon_t with n-1 (751-1=750) degrees of freedom
arch1LogReturnsSTD <- garchFit(formula = ~ garch(1, 0), data = logReturns, cond.dist = "std")
summary(arch1LogReturnsSTD)
acf(residuals(arch1LogReturnsSTD), na.action=na.remove)
pacf(residuals(arch1LogReturnsSTD), na.action=na.remove)
plot(residuals(arch1LogReturnsSTD))
pautocorr.test(residuals(arch1LogReturnsSTD),lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)

model = ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1, 0),
  submodel = NULL, external.regressors = NULL, variance.targeting = FALSE),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE, archm = FALSE,
  archpow = 1, arfima = FALSE, external.regressors = NULL, archex = FALSE),
  distribution.model = "std", start.pars = list(), fixed.pars = list())
fit = ugarchfit(model, logReturns)
fit
acf(residuals(fit), na.action=na.remove)
pacf(residuals(fit), na.action=na.remove)
plot(residuals(fit))
pautocorr.test(residuals(fit),lagmax=10,method='all',alpha = 0.05,L=30,B=2000, digits=3, print=TRUE)
```




```{r}
#4

path <- "C:/Users/mykul/Downloads/"
file <- paste(path,"m-intc7308.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)

df <- data

df["date"] <- as.Date(as.character(data[["date"]]) , format = "%Y%m%d")
intelLogReturns <- log(data["rtn"]+1)

GARCH_1_0_intelLogReturns <- garchFit(formula = ~garch(1,0), data = intelLogReturns, trace = F)
summary(GARCH_1_0_intelLogReturns)
# Information Criterion Statistics:
#     AIC       BIC       SIC      HQIC 
# -1.319717 -1.291464 -1.319813 -1.308563 


# GARCH(1,1) HAS THE LOWEST AIC AND LOWEST BIC
GARCH_1_1_intelLogReturns <- garchFit(formula = ~garch(1,1), data = intelLogReturns, trace = F)
summary(GARCH_1_1_intelLogReturns)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -1.370234 -1.332563 -1.370403 -1.355361 
      
      
GARCH_2_1_intelLogReturns <- garchFit(formula = ~garch(2,1), data = intelLogReturns, trace = F)
summary(GARCH_2_1_intelLogReturns)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -1.367194 -1.320106 -1.367458 -1.348604 

      

GARCH_1_2_intelLogReturns <- garchFit(formula = ~garch(1,2), data = intelLogReturns, trace = F)
summary(GARCH_1_2_intelLogReturns)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -1.367169 -1.320080 -1.367432 -1.348578 
      
      

GARCH_2_2_intelLogReturns <- garchFit(formula = ~garch(2,2), data = intelLogReturns, trace = F)
summary(GARCH_2_2_intelLogReturns)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -1.362539 -1.306033 -1.362918 -1.340231 
      
      
predict(GARCH_1_1_intelLogReturns, n.ahead = 3)
#   meanForecast meanError  standardDeviation
#   0.01073352	0.1183990	0.1183990		
#   0.01073352	0.1187943	0.1187943		
#   0.01073352	0.1191642	0.1191642


```

```{r}
# 5
path <- "C:/Users/mykul/Downloads/"
file <- paste(path,"d-gmsp9908.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)

df <- data

df["date"] <- as.Date(as.character(data[["date"]]) , format = "%Y%m%d")

spLogReturns <- log(data["sp"]+1)
gmLogReturns <- log(data["gm"]+1)

# 5 (i)
Box.test(df["gm"]^2, lag = 10, type = c("Ljung-Box"), fitdf = 0) 

# all p-values below 0.05
Box.test(gmLogReturns, lag = 10, type = c("Ljung-Box"), fitdf = 0)
Box.test(gmLogReturns^2, lag = 10, type = c("Ljung-Box"), fitdf = 0) # does squared returns mean squared log returns? no 
Box.test(df["gm"], lag = 10, type = c("Ljung-Box"), fitdf = 0)




```


```{r}
# 5 (ii)
spSquaredLogReturns <- log(data["sp"]+1)^2
acf(spSquaredLogReturns)
pacf(spSquaredLogReturns)

gmSquaredLogReturns <- log(data["gm"]+1)^2
acf(gmSquaredLogReturns)
pacf(gmSquaredLogReturns)
```




```{r}
# 5 (iii)
# GARCH(1,1) HAS THE LOWEST AIC AND LOWEST BIC
GARCH_1_1_gmLogReturnss <- garchFit(formula = ~garch(1,1), data = gmLogReturns, trace = F, cond.dist = "norm")
summary(GARCH_1_1_gmLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -4.552447 -4.543174 -4.552452 -4.549082 
      
      
GARCH_2_1_gmLogReturnss <- garchFit(formula = ~garch(2,1), data = gmLogReturns, trace = F, cond.dist = "norm")
summary(GARCH_2_1_gmLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -4.551665 -4.540074 -4.551672 -4.547458 

      
GARCH_1_2_gmLogReturnss <- garchFit(formula = ~garch(1,2), data = gmLogReturns, trace = F, cond.dist = "norm")
summary(GARCH_1_2_gmLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -4.551831 -4.540240 -4.551839 -4.547624 
      
      

GARCH_2_2_gmLogReturnss <- garchFit(formula = ~garch(2,2), data = gmLogReturns, trace = F, cond.dist = "norm")
summary(GARCH_2_2_gmLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -4.551036 -4.537127 -4.551047 -4.545988 
      
      

```




```{r}
# 5 (iv)


AR_5_GARCH_1_1_spLogReturnss <- garchFit(formula = ~arma(5,0)+garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(AR_5_GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.248452 -6.227589 -6.248478 -6.240880 


AR_4_GARCH_1_1_spLogReturnss <- garchFit(formula = ~arma(4,0)+garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(AR_4_GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.246305 -6.227760 -6.246325 -6.239574 
      

AR_3_GARCH_1_1_spLogReturnss <- garchFit(formula = ~arma(3,0)+garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(AR_3_GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.246901 -6.230674 -6.246916 -6.241012
      
      

AR_2_GARCH_1_1_spLogReturnss <- garchFit(formula = ~arma(2,0)+garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(AR_2_GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.246348 -6.232440 -6.246360 -6.241300
      

# AR(1)-GARCH(1,1) is a simpler model and has the best overall performance considering AIC, BIC, SIC, HQIC
AR_1_GARCH_1_1_spLogReturnss <- garchFit(formula = ~arma(1,0)+garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(AR_1_GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.245335 -6.233745 -6.245343 -6.241129

# in fact, even GARCH(1,1) doesn't perform horribly
GARCH_1_1_spLogReturnss <- garchFit(formula = ~garch(1,1), data = spLogReturns, trace = F, cond.dist = "norm")
summary(GARCH_1_1_spLogReturnss)
# Information Criterion Statistics:
#      AIC       BIC       SIC      HQIC 
# -6.243305 -6.234032 -6.243310 -6.239939 
      

```









