---
title: "Untitled"
author: "Michael Wieck-Sosa"
date: "11/28/2020"
output:
  pdFonesdocument: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1(i)
# phi: p x p matrix
# Xt: p x 1 matrix
# phi * Xt: p x 1 
# eps: p x 1 matrix

library(matlab)
p <- 100
n <- 50 
phi <- 0.5*diag(p) # p x p matrix

lambda <- matrix(nrow=p,ncol=p) # p x p matrix
for(i in 1:p){
  for(j in 1:p){
    lambda[i,j] <- 0.3^abs(i-j)
  }
}

eps <- matrix(rnorm(n=p,mean=0,sd=lambda),nrow=p,ncol=1) # p x 1 matrix

Xt <- zeros((size(matrix(nrow=p,ncol=1)))) # start at zero
for(i in 1:p){
  Xt <- phi %*% Xt + eps
}

mu <- mean(Xt)
gamma_zero <- (Xt-mu) %*% t((Xt-mu))
gamma_zero

```

```{r}
#1(ii)
# phi: p x p matrix
# Xt: p x 1 matrix
# phi * Xt: p x 1 
# eps: p x 1 matrix
library(matlab)

simNumVec <- c()
minEstErrorVec <- c()
minUVec <- c()

for(simNumber in 1:100){
  
  
  
  p <- 100
  n <- 50 
  phi <- 0.5*diag(p) # p x p matrix
  
  lambda <- matrix(nrow=p,ncol=p) # p x p matrix
  for(i in 1:p){
    for(j in 1:p){
      lambda[i,j] <- 0.3^abs(i-j)
    }
  }
  
  
  eps <- matrix(rnorm(n=p,mean=0,sd=lambda),nrow=p,ncol=1) # p x 1 matrix
  
  Xt <- zeros((size(matrix(nrow=p,ncol=1)))) # start at zero
  Xt
  for(i in 1:p){
    Xt <- phi %*% Xt + eps
    Xt
  }
  Xt
  
  mu <- mean(Xt)
  gamma_zero <- (Xt-mu) %*% t((Xt-mu))
  gamma_zero
  
  
  minEstimationError <- 1e10
  
  minU <- 0
  Tu <- matrix(nrow=p,ncol=p)
  for(u in seq(0,1,by=1e-2)){
    for(i in 1:p){
      for(j in 1:p){
        if(abs(lambda[i,j]) >= u){
          Tu[i,j] <- lambda[i,j]
        }else{
          Tu[i,j] <- 0
        }
      }
    }
    estimationError <- (norm(Tu - gamma_zero,type="F")^2)/p
    if(estimationError < minEstimationError){
      minEstimationError <- estimationError
      minU <- u 
    }
  }
  print(paste0("Simulation ",simNumber," has minimum estimation error = ",minEstimationError, " with u = ",minU))
  simNumVec[simNumber] <- simNumber
  minEstErrorVec[simNumber] <- minEstimationError
  minUVec[simNumber] <- minU
}

dfEstError <- data.frame(simNumVec,minEstErrorVec,minUVec)
names(dfEstError) <- c("Simulation Number","Min Estimation Error","Min u")

```


```{r}
#2(i)
p <- 20
I_p <- diag(p) # p x p identity matrix
J_p <- matlab::ones(p,p) # p x p matrix of ones
sigma <- I_p + J_p # std matrix
eps_i <- rnorm(n=100,mean=0,sd=sigma) # 
delta_n <- c(rep(0,100))
Xi <- delta_n + eps_i
n <- 100
s <- 15
TstarVec <- c()

# run 100 simulations 
for(i in 1:100){
  ei <- rnorm(n=100,mean=0,sd=1)
  
  Xbar_neg_S <- sum(Xi[1:s])/s
  leftSum <- ei * sum(Xi[1:s]-Xbar_neg_S)
  leftConstant <- ((n-s)/(n*s))^(1/2)
  leftQ <- leftConstant * leftSum
  
  Xbar_pos_s <- sum(Xi[s:n])/(n-s)
  rightSum <- ei * sum(Xi[(s+1):n]-Xbar_pos_s)
  rightConstant <- (s/(n*(n-s)))^(1/2)
  rightQ <- rightConstant * rightSum
  
  Zstar_ns <- leftQ - rightQ # length 100 vector 
  
  Tstar_n <- norm(matrix(Zstar_ns[s:(n-s)]),type="I") 
  
  TstarVec[i] <- Tstar_n
}


alphaList <- c(0.05,0.1)
tVec <- seq(0,0.2,by=0.001)
res <- c()
for(alpha in alphaList){
  print(paste0("alpha = ",alpha))
  for(i in 1:length(tVec)){
    pr <- length(TstarVec[TstarVec <= tVec[i]]) / length(TstarVec)
    if(pr >= (1-alpha)){
      res[i] <- tVec[i]
    }else{
      res[i] <- NA
    }
  }
  q <- min(res,na.rm=TRUE)
  print(paste0("q = ",q))
  
  # reject if Tn > q
  # by Them 1 approx T_nn by Tstar_n under h)
  rejectCounter <- 0
  TnRejectedVec <- c()
  for(i in 1:length(TstarVec)){
    if(TstarVec[i] > q){
      rejectCounter <- rejectCounter + 1
      TnRejectedVec[i] <- TstarVec[i]
    }
  }
  empericalRejectFraction <- rejectCounter / length(TstarVec)
  print(paste0("The empirically rejected fraction for alpha = ",alpha," is ",rejectCounter," / ",length(TstarVec)," = ",empericalRejectFraction))
}




```

```{r}
#2(ii)
p <- 20
I_p <- diag(p) # p x p identity matrix
J_p <- matlab::ones(p,p) # p x p matrix of ones
sigma <- I_p + J_p # std matrix
eps_i <- rnorm(n=100,mean=0,sd=sigma)
delta_n <- c(rep(0.8,5),rep(0,95))
Xi <- delta_n + eps_i
m <- 40

n <- 100
s <- 15
TstarVec <- c()

# run 100 simulations 
for(i in 1:100){
  ei <- rnorm(n=100,mean=0,sd=1)
  
  Xbar_neg_S <- sum(Xi[1:s])/s
  leftSum <- ei * sum(Xi[1:s]-Xbar_neg_S)
  leftConstant <- ((n-s)/(n*s))^(1/2)
  leftQ <- leftConstant * leftSum
  
  Xbar_pos_s <- sum(Xi[s:n])/(n-s)
  rightSum <- ei * sum(Xi[(s+1):n]-Xbar_pos_s)
  rightConstant <- (s/(n*(n-s)))^(1/2)
  rightQ <- rightConstant * rightSum
  
  Zstar_ns <- leftQ - rightQ # length 100 vector 
  
  Tstar_n <- norm(matrix(Zstar_ns[s:(n-s)]),type="I") 
  
  TstarVec[i] <- Tstar_n
}


alphaList <- c(0.05,0.1)
tVec <- seq(0,0.2,by=0.001)
res <- c()
for(alpha in alphaList){
  for(i in 1:length(tVec)){
    pr <- length(TstarVec[TstarVec <= tVec[i]]) / length(TstarVec)
    if(pr >= (1-alpha)){
      res[i] <- tVec[i]
    }else{
      res[i] <- NA
    }
  }
  q <- min(res,na.rm=TRUE)
  #print(paste0("q = ",q))
  
  # reject if Tn > q
  rejectIndexVec <- c()
  TnRejectedVec <- c()
  for(i in 1:length(TstarVec)){
    if(TstarVec[i] > q){
      rejectIndexVec[i] <- i
      TnRejectedVec[i] <- TstarVec[i]
    }
  }


  
  power <- length(rejectIndexVec[!is.na(rejectIndexVec) & rejectIndexVec <= 5]) / 5

  print(paste0("The power of the statistical test for alpha = ",alpha," is ",power))
}




```


```{r}
#2(iii)
squaredError <- c()

for(it in 1:100){
  p <- 20
  I_p <- diag(p) # p x p identity matrix
  J_p <- matlab::ones(p,p) # p x p matrix of ones
  sigma <- I_p + J_p # std matrix
  eps_i <- rnorm(n=100,mean=0,sd=sigma)
  delta_n <- c(rep(0.8,5),rep(0,95))
  Xi <- delta_n + eps_i
  m <- 40
  
  n <- 100
  s <- 15
  
  theta <- 1/2
  sVec <- seq(1,n,1)
  zVec <- c()
  for(i in 1:(length(sVec)-1)){
    const <- ((sVec[i]*(n-sVec[i])/n)^(1-theta))
    sumVal <- (sum(Xi[1:sVec[i]])/sVec[i] - sum(Xi[(sVec[i]+1):n])/(n-sVec[i]))
    zVec[i] <- const*sumVal
  }
  
  norm(matrix(zVec),type="I")==max(abs(matrix(zVec))) # TRUE
  mhat_theta <- sVec[which.max(abs((matrix(zVec))))]
  t_mhat <- mhat_theta / n
  t_m <- m / n 
  squaredError[it] <- (t_mhat - t_m)^2
  
}

squaredError
mean(squaredError)

```

```{r}
#3(i)
library(Ryacas)
library(psych)

path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-fac-ex-9008.txt",sep="")
x <- read.table(file, sep = '',header = TRUE)


betaVec <- c()
rSquaredVec <- c()
sp5 <- x$SP5
for (stock in names(x[1:13])){

  stockData <- unlist(x[stock],use.names = FALSE)
  
  fit <- lm(formula = stockData ~ sp5)
  
  betaVec <- c(betaVec, fit$coefficients[2])
  rSquaredVec <- c(rSquaredVec,summary(fit)$r.squared)
}
names(betaVec) <- names(x[1:13])
betaVec
names(rSquaredVec) <- names(x[1:13])
rSquaredVec


```

```{r}
#3(i)

# matrix algebra gives same results

path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-fac-ex-9008.txt",sep="")
x <- read.table(file, sep = '',header = TRUE)
rtn <- x[1:13]
xmtx <- cbind(ones = 1, x$SP5)
xit.hat <- t(rtn) %*% xmtx %*% solve(t(xmtx) %*% xmtx)  
beta.hat <- xit.hat[, 2]  
print(beta.hat)
E.hat <- t(t(rtn) - xit.hat %*% t(xmtx)) 
D.hat <- diag(crossprod(E.hat)/(nrow(x)-2))
rsquared <- 1 - (D.hat / diag((var(rtn))))
print(rsquared)

```




```{r}
#4(i)

library(ggfortify)
path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-mrk2vw.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)
x <- data[2:length(data)]


# the the eigenvalues of the covariance matrix
# are equal to the variance of the principal components
(eigen(cov(x))$values)^(1/2)
# 12.876746  8.242062  5.085315  4.866989  4.373461  2.486548

# proportion of variance explained 
for (val in (eigen(cov(x))$values)) {
  print(val / sum(eigen(cov(x))$values))
}

# the eigenvectors of the covariance matrix
# are equal to the principal components with some possible opposite pos/neg signs 
eigen(cov(x))$vectors

pca <- prcomp(x,scale=FALSE)

# Standard deviations (1, .., p=6):
# 12.876746  8.242062  5.085315  4.866989  4.373461  2.486548

#Rotation (n x k) = (6 x 6):
#          PC1        PC2         PC3        PC4         PC5         PC6
#MRK 0.2482674  0.6318320  0.37197744 -0.4748706  0.41566372 -0.05005996
#JNJ 0.2217986  0.5229315  0.04048949  0.1616380 -0.79493661 -0.13288192
#GE  0.3426374  0.2628869 -0.58678851  0.4449824  0.38731060 -0.34806679
#GM  0.5569254 -0.3370466 -0.38061137 -0.6209397 -0.19867105 -0.07957657
#F   0.6258047 -0.3463563  0.57847193  0.3820210  0.06411089 -0.06103904
#VW  0.2645203  0.1570299 -0.19020472  0.1373154  0.04134679  0.92120992

pca
plot(pca,main="Variance Explained by Principal Components")
ggplot2::autoplot(pca)+ggtitle("Principal Components 1 and 2 of m-mrk2vw Data")


```



```{r}
#4(ii)

path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-mrk2vw.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)
x <- data[2:length(data)]



(eigen(cor(x))$values)^(1/2)

# proportion of variance explained 
for (val in (eigen(cor(x))$values)) {
  print(val / sum(eigen(cor(x))$values))
}

eigen(cor(x))$vectors

pca <- prcomp(x,scale=TRUE)

pca
plot(pca,main="Variance Explained by Principal Components")
ggplot2::autoplot(pca)+ggtitle("Principal Components 1 and 2 of m-mrk2vw Data")




```
```{r}
#4(iii)

library(psych)
path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-mrk2vw.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)
head(data)
x <- data[2:length(data)]


factorAnalysis <- principal(x,nfactors=2,rotate='none',covar = TRUE)
factorAnalysis
plot(factorAnalysis)




library(xts)
library(covFactorModel)
path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-mrk2vw.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)
x <- data[2:length(data)]
factor_model <- factorModel(xts(x,order.by=as.Date(seq(nrow(x)))), type = "Stat-PCA",K=2)
#factor_model
  

gammaFactorModel <- cbind(alpha = factor_model$alpha, beta = factor_model$beta[,])
gammaFactorModel



```
```{r}
factorAnalysisCorr
```

```{r}
factorAnalysisCovar
```


```{r}
factor_model

```

```{r}
#5(i)

# method 1: linear eqn with betas and r2 for each variable
path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-excess-c10sp-9003.txt",sep="")
x <- read.table(file, sep = '',header = TRUE)
head(x)
betaVec <- c()
rSquaredVec <- c()
sp5 <- x$SP5
for (stock in names(x[1:10])){

  
  stockData <- unlist(x[stock],use.names = FALSE)
  
  fit <- lm(formula = stockData ~ sp5)
  
  
  betaVec <- c(betaVec, fit$coefficients[2])
  rSquaredVec <- c(rSquaredVec,summary(fit)$r.squared)
}
names(betaVec) <- names(x[1:10])
#betaVec
sort(betaVec,decreasing = TRUE)
barplot(sort(betaVec,decreasing = TRUE),main="Factor Loading Beta Estimates for Stocks")

names(rSquaredVec) <- names(x[1:10])
#rSquaredVec
sort(rSquaredVec,decreasing = TRUE)
barplot(sort(rSquaredVec,decreasing = TRUE),main="R-Squared for Stocks")
```

```{r}
#5(i)
path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-excess-c10sp-9003.txt",sep="")
x <- read.table(file, sep = '',header = TRUE)
rtn <- x[1:10]
xmtx <- cbind(ones = 1, x$SP5)
xit.hat <- t(rtn) %*% xmtx %*% solve(t(xmtx) %*% xmtx)  
beta.hat <- xit.hat[, 2]  
print(sort(beta.hat,decreasing = TRUE))
E.hat <- t(t(rtn) - xit.hat %*% t(xmtx)) 
D.hat <- diag(crossprod(E.hat)/(nrow(x)-2))
rsquared <- 1 - (D.hat / diag((var(rtn))))
print(sort(rsquared,decreasing = TRUE))



```
```{r}
library(covFactorModel)
factor_model <- factorModel(xts(rtn,order.by=as.Date(seq(nrow(rtn)))), type = "M", econ_fact = as.matrix(xmtx))

  

gammaFactorModel <- cbind(alpha = factor_model$alpha, beta = factor_model$beta[,])
gammaFactorModel

```

```{r}
#5(ii)
file <- paste(path,"m-excess-c10sp-9003.txt",sep="")
x <- read.table(file, sep = '',header = TRUE)


sum(diag(cov(x[,1:10])))

eigen(cov(x[,1:10]))


# explained variance for each value
for (s in eigen(cov(x[,1:10]))$values) {
  print(s / sum(eigen(cov(x[,1:10]))$values))
}

plot(eigen(cov(x[,1:10]))$values, xlab = 'Principal Component Number', ylab = 'Eigenvalue', main = 'Scree Plot')
lines(eigen(cov(x[,1:10]))$values)


```


```{r}
#6
library(covFactorModel)
library(xts)

path <- "C:/Users/mykul/OneDrive/Documents/stat429/hw5/"
file <- paste(path,"m-fedip.txt",sep="")
macrodata <- read.table(file, sep = '',header = TRUE)
macrodata <- macrodata[427:nrow(macrodata),3:4]
head(macrodata)
# subset from january 1990 to December 2003


# from January 1990 to December 2003
file <- paste(path,"m-excess-c10sp-9003.txt",sep="")
data <- read.table(file, sep = '',header = TRUE)
head(data)
X <- data[1:10]
head(X)

fm <- factorModel(xts(X,order.by = as.Date(seq(nrow(X)))), type = "Macro", econ_fact = as.matrix(macrodata))

cbind(alpha = fm$alpha, beta = fm$beta)






```

